create_clock -period 10 [get_ports clk]
set_clock_transition 0.1 [get_clocks clk]
set_clock_uncertainty -setup 0.2 [get_clocks clk]
set_clock_uncertainty -hold 0.1 [get_clocks clk]
set_input_delay  -clock clk -max 2.0 [get_ports {valid_in clr_acc a_in* w_in* bias_in*}]
set_input_delay  -clock clk -min 0.5 [get_ports {valid_in clr_acc a_in* w_in* bias_in*}]
set_output_delay  -clock clk -max 2.0 [get_ports {valid_out act_out* cos_out*}]
set_output_delay  -clock clk -min 0.5 [get_ports {valid_out act_out* cos_out*}]
set_false_path -from [get_ports rst_in]
set_load 0.05 [all_outputs]

